package com.aisolutions.bloodcare.Details;/*
Created by Akila Ishan on 2021-05-17.
*/

import java.util.ArrayList;

public class ArraySets {


    public ArraySets() {

    }

    public String[] province = {"Your Province", "Central", "Eastern", "North Central", "Northern", "North Western", "Sabaragamuwa", "Southern", "Uva", "Western"};


    //--9 provinces
    public String[] districts_Central = {"Your District", "Kandy", "Matale", "Nuwara Eliya"};
    public String[] districts_Eastern = {"Your District", "Ampara", "Batticaloa", "Trincomalee"};
    public String[] districts_North_Central = {"Your District", "Anuradhapura", "Polonnaruwa"};
    public String[] districts_Northern = {"Your District", "Jaffna", "Kilinochchi", "Mannar", "Mulativu", "Vavuniya"};
    public String[] districts_North_Western = {"Your District", "Kurunegala", "Puttalam"};
    public String[] districts_Sabaragamuwa = {"Your District", "Kegalle", "Ratnapura"};
    public String[] districts_Southern = {"Your District", "Galle", "Hambantota", "Matara"};
    public String[] districts_Uva = {"Your District", "Badulla", "Monaragala"};
    public String[] districts_Western = {"Your District", "Colombo", "Gampaha", "Kalutara"};


    //--25 districts
    public String[] city_Kandy = {"Your City", "Akurana", "Aladeniya", "Alawatugoda", "Aludeniya", "Ambatenna", "Ampitiya", "Ankubura", "Ankumbura", "Aruppola", "Atabage", "Balana", "Batugoda", "Bawlana", "Bopana", "Danthure", "Daulagala", "Dedunupitiya", "Deltota", "Digana", "Doluwa", "Doragamuwa", "Etulgama", "Galaboda", "Galagedara", "Galaha", "Galhinna", "Gampola ", "Gelioya", "Godamunna", "Gonagantenna", "Guhagoda", "Gunnepana", "Gurudeniya", "Haguranketha", "Halloluwa ", "Handaganawa", "Handessa", "Hanguranketha", "Haragama", "Harankahawa", "Harispattuwa", "Hasalaka", "Hatharaliyadda ", "Hewaheta", "Hindagala", "Hondiyadeniya", "Hunnasgiriya", "Jambugahapitiya", "Kadugannawa", "Kahataliyadda ", "Kalugala", "Kandy Town", "Kapuliyadde", "Karandagolla", "Katugastota", "Kengalla", "Ketakumbura", "Kiribathkumbura ", "Kolongoda", "Kulugammana", "Kumbukkandura", "Kundasale", "Leemagahakotuwa", "Lewella", "Lunuketiya Maditta", "Madawala ", "Madugalla", "Madulkele", "Mahadoraliyadda", "Mahaiyawa", "Mahamedagama", "Mailapitiya", "Makuldeniya", "Mandaram Nuwara ", "Marassana", "Maturata", "Mawatura", "Mawilmada", "Medamahanuwara", "Medawala Harispattuwa", "Menikdiwela ", "Menikhinne", "Mimure", "Minigamuwa", "Minipe", "Muruthalawa", "Naranpanawa", "Nattarampotha", "Nawalapitiya", "Nugaliyadda", "Nugawela", "Pallekele", "Pallekotuwa", "Panwilatenna", "Paradeka", "Pasbage", "Pattitalawa", "Peradeniya", "Pilawala", "Pilimthalawa", "Poholiyadda", "Polgolla", "Poththapitiya", "Pujapitiya", "Pupuressa", "Pussellawa", "Rajawella", "Rambukpitiya", "Rangala", "Rantembe", "Rathukohodigala", "Rikillagaskada", "Sangarajapura", "Senarathwela", "Talatuoya", "Teldeniya", "Thalatuoya", "Thawalanthenna", "Thennekubura", "Udahentenna", "Udahingulwala ", "Uda Peradeniya", "Udawatta", "Ududumbara", "Uduwa", "Uduwahinna", "Uduwela", "Ulapane", "Ulpothagama ", "Unuwinna", "Velamboda", "Wattappola", "Wattegama", "Weligalla", "Weligampola", "Wendaruwa", "Werellagama", "Wettawa", "Wilanagama", "Yahalatenna", "Yatihalagala"};
    public String[] city_Matale = {"Your City", "Akuramboda", "Alawatta", "Ambana", "Ataragallewa", "Bambaragaswewa", "Beligamuwa", "Dambulla", "Dankanda", "Devagiriya", "Dewahuwa", "Dullewa", "Dunkolawatta", "Dunuwilapitiya", "Elkaduwa", "Erawula Junction", "Etanawala", "Galewela", "Gammaduwa", "Gangala", "Gangala Puwakpitiya", "Handungamuwa", "Hattota Amuna", "Hettipola", "Ilukkumbura", "Imbulgolla", "Inamaluwa", "Kaikawala", "Kalundawa", "Kandalama", "Karagahinna", "Katudeniya", "Kavudupelella", "Kibissa", "Kiwula", "Kongahawela", "Laggala Pallegama", "Leliambe", "Lenadora", "Madawala Ulpotha", "Madipola", "Mahawela", "Mananwatta", "Maraka", "Matale", "Matale Town", "Melipitiya", "Metihakka", "Millawana", "Muwandeniya", "Nalanda", "Na ula", "Nugagolla", "Opalgala", "Ovilikanda", "Palapathwela", "Pallepola", "Perakanatta", "Pubbiliya", "Ranamuregama", "Rattota", "Selagama", "Sigiriya", "Talagoda Junction", "Talakiriyagama", "Udasgiriya", "Udatenna", "Ukuwela", "Wahacotte", "Walawela", "Wehigala", "Welangahawatte", "Wewalawewa", "Yatawatta"};
    public String[] city_Nuwara_Eliya = {"Your City", "Adhikarigama", "Agarapatana", "Ambagamuwa Udabulathgama", "Ambatalawa", "Ambewela", "Bambarakelle", "Barawardhanaoya", "Bogawantalawa", "Bopattalawa", "Dagampitiya", "Dayagama Bazaar", "Degampitiya", "Dikoya", "Doragala", "Dunukedeniya", "Ginigathena", "Gonakele", "Hakgala", "Halgran Oya", "Hangarapitiya", "Hapugastalawa", "Harangalagama", "Harasbedda", "Hatton", "Hawa Eliya", "Hedunuwewa", "Hitigegama", "Idamegama", "Kalaganwatta", "Kandapola", "Katukitula", "Keerthi Bandarapura", "Kelanigama", "Ketaboola", "Kotagala", "Kotmale", "Kottellena", "Kumbalgamuwa", "Kumbukwela", "Kurupanawela", "Labookelle", "Labukele", "Laxapana", "Lindula", "Madulla", "Magastota", "Maldeniya", "Maskeliya", "Maswela", "Meethalawa", "Mipanawa", "Mipilimana", "Morahenagama", "Munwatta", "Nanuoya", "Nawathispane", "Nildandahinna", "Norwood", "Nuwara Eliya", "Nuwara Eliya Town", "Padiyapelella", "Palena", "Patana", "Pitawala", "Pundaluoya", "Pussalamankada", "Radella", "Ragala", "Ramboda", "Rozella", "Rupaha", "Ruwaneliya", "Sadathenna", "Santhipura", "Talawakele", "Teripeha", "Udamadura", "Udapussallawa", "Walapane", "Watagoda", "Watagoda Hanspattuwa", "Watawala", "Widulipura", "Wijebahukanda"};

    public String[] city_Ampara = {"Your City", "Addalaichenai", "Akkaraipattu", "Ampara", "Ampara Town", "Bakmitiyawa", "Central Camp", "Dadayamtalawa", "Damana", "Damanewela", "Deegawapiya", "Dehiattakandiya", "Digamadulla", "Dorakumbura", "Gonagolla", "Hingurana", "Hulannuge", "Irakkamama", "Kalmunai", "Karativu", "Koknahara", "Kolamanthalawa", "Komari", "Lahugala", "Mahaoya", "Malwatta", "Mangalagama", "Marathamune", "Moragahapallama", "Namaloya", "Navithanveli", "Nawamedagama", "Nintavur", "Oluvil", "Padiyathalawa", "Pahalalanda", "Palamunai", "Panama", "Pannalagama", "Periyaneelavanai", "Pottuvil", "Rajagalatenna", "Sainthamaruthu", "Sammanthurai", "Serankada", "Siripura", "Siyambalawewa", "Tempitiya", "Thambiluvil", "Tirukkovil", "Uhana"};
    public String[] city_Batticaloa = {"Your City", "Ampilanthurai", "Araipattai", "Ayithiyamalai", "Bakiella", "Batticaloa Town", "Cheddipalayam", "Chenkaladi", "Eravur", "Kalkudah", "Kallar", "Kaluwanchikudi", "Kaluwankemy", "Kannankudah", "Karadiyanaru", "Kathiraveli", "Kattankudy", "Kiran", "Kirankulam", "Koddaikallar", "Koddamunai", "Kokkaddichcholai", "Kurukkalmadam", "Mandur", "Mankemi", "Miravodai", "Murakottanchanai", "Navagirinagar", "Navatkadu", "Oddamavadi", "Panichankemi", "Pankudavely", "Periyaporativu", "Periyapullumalai", "Pillaiyaradi", "Puliyanthivu", "Punanai", "Puthukudiyiruppu", "Puthur", "Thannamunai", "Thettativu", "Thikkodai", "Thirupalugamam", "Thuraineelavanai", "Unnichchai", "Vakaneri", "Vakarai", "Valaichenai", "Vantharumoolai", "Vellavely"};
    public String[] city_Trincomalee = {"Your City", "Agbopura", "Anna Nagar", "Arunagiri Nagar", "Buckmigama", "Chinabay", "Dehiwatte", "Deva Nagar", "Echchilampattai", "Galmetiyawa", "Gomarankadawala", "Kaddaiparichchan", "Kanniya", "Kantale", "Kavaddikudah", "Kiliveddy", "Kinniya", "Kuchchaveli", "Kumburupiddy", "Kurinchakemy", "Lankapatuna", "Linganagar", "Mahadivulwewa", "Maharugiramam", "Mallikativu", "Matikali", "Mawadichchenai", "Mihindapura", "Mullipothana", "Murugapuri", "Mutur", "Neelapola", "Nelsonpura", "Nilaveli", "Nithiyapuri", "Orrs Hill", "Palaiyoothu", "Pankulam", "Rottawewa", "Sampaltivu", "Sampur", "Samudragama", "Serunuwara", "Seruwila", "Sirajnagar", "Somapura", "Tampalakamam", "Thirukadaloor", "Tiriyayi", "Toppur", "Trincomalee Town", "Uppaveli", "Vellamanal", "Wanela"};

    public String[] city_Anuradhapura = {"Your City", "Andiyagala", "Anuradhapura Town", "Awukana", "Dematawewa", "Dunumadalawa", "Elayapattuwa", "Eppawala", "Etaweeragollewa", "Galenbindunuwewa", "Galkadawala", "Galkiriyagama", "Galnewa", "Gambirigaswewa", "Gemunupura", "Gonahaddenawa", "Habarana", "Halmillawetiya", "Halmillewa", "Hidogama", "Horowpothana", "Hurulunikawewa", "Ihalagama", "Ipalogama", "Ipologama", "Kahatagasdigiliya", "Kahatagasdigliya", "Kalaoya", "Kalawedi Ulpotha", "Karagahawewa", "Kebithigollawa", "Kekirawa", "Kendewa", "Kirigalwewa", "Madatugama", "Mahabulankulama", "Maha Elagamuwa", "Mahailluppallama", "Mahawilachchiya", "Mailagaswewa", "Maneruwa", "Maradankadawala", "Medawachchiya", "Meegodawewa", "Megodawewa", "Mihintale", "Morakewa", "Nachchaduwa", "Nochchiyagama", "Nuwaragam Palatha", "Padavi Siripura", "Padavi Siritissapura", "Padaviya", "Parakumpura", "Parangiyawadiya", "Parasangahawewa", "Pemaduwa", "Pulmoddai", "Rajanganaya", "Rambewa", "Ranorawa", "Saliyapura", "Siyambalewa", "Talawa", "Tambuttegama", "Telhiriyawa", "Thalawa", "Thambuttegama", "Thanthirimale", "Thirappane", "Tittagonewa", "Udunuwara Colony", "Wahalkada", "Welimuwapotana", "Welioya Project"};
    public String[] city_Polonnaruwa = {"Your City", "Aluthwewa", "Alutwewa", "Aralangawila", "Aselapura", "Attanakadawala", "Bakamuna", "Dalukana", "Damminna", "Dewagala", "Dimbulagala", "Divulankadawala", "Divuldamana", "Diyabeduma", "Diyasenpura", "Elahera", "Ellewewa", "Galamuna", "Galoya Junction", "Giritale", "Hansayapalama", "Hingurakdamana", "Hingurakgoda", "Jayanthipura", "Jayasiripura", "Kalingaela", "Kalukele Badanagala", "Kashyapapura", "Kawudulla", "Kawuduluwewa", "Kottapitiya", "Kumaragama", "Lakshauyana", "Maduruoya", "Maha Ambagaswewa", "Mahatalakolawewa", "Mahawela Sinhapura", "Mampitiya", "Manampitiya", "Medirigiriya", "Meegaswewa", "Minneriya", "Mutugala", "Nawasenapura", "Nelumwewa", "Nuwaragala", "Onegama", "Orubendi Siyambalawa", "Palugasdamana", "Parakrama Samudraya", "Pelatiyawa", "Pimburattewa", "Polonnaruwa Town", "Pulastigama", "Sevanapitiya", "Sinhagama", "Sungavila", "Talpotha", "Tamankaduwa", "Tambala", "Unagalavehera", "Welikanda", "Wijayabapura", "Yodaela", "Yudaganawa"};

    public String[] city_Jaffna = {"Your City", "Chavakachcheri", "Delft Island", "Jaffna Town", "Kankesanthurai", "Karainagar", "Kayts", "Kokuvil", "Mandaitivu", "Maviddapuram", "Nallur", "Point Pedro", "Puloly", "Vadamaradchy", "Valikamam East", "Valikamam North", "Valikamam South", "Valikamam West", "Valvettithurai"};
    public String[] city_Kilinochchi = {"Your City", "Aliyavalai", "Kilinochchi", "Parantan", "Pooneryn"};
    public String[] city_Mannar = {"Your City", "Mannar", "Pesalai", "Thalaimannar"};
    public String[] city_Mulativu = {"Your City", "Alampil", "Karuppaddamurippu", "Mankulam", "Mulativu Town", "Mullivaikkal", "Mulliyawalai", "Muththaiyankaddukulam", "Naddan Kandal", "Oddusuddan", "Puthukkudiyiruppu", "Puthuvedduvan", "Thunukkai", "Udayarkaddu", "Vavunakkulam", "Visvamadukulam", "Yogapuram"};
    public String[] city_Vavuniya = {"Your City", "Akkarayankulam", "Elephant Pass", "Eluthumadduval", "lyyakachchi", "Kavutharimunai", "Mulliyan", "Murasumoddai", "Nedunkerny", "Omanthai", "Pallai", "Paranthan", "Puliyankulam", "Purakari Nallur", "Ramanathapuram", "Sivapuram", "Skanthapuram", "Thalaiyadi", "Uruthirapuram", "Vaddakachchi", "Vavuniya Town", "Veravil"};

    public String[] city_Kurunegala = {"Your City", "Alawwa", "Ambanpola", "Ataragalla", "Awulegama", "Balalla", "Bamunukotuwa", "Bandara Koswatta", "Bogahamulla", "Bopitiya", "Bujjomuwa", "Dambadeniya", "Deegalla", "Demataluwa", "Diddeniya", "Divullegoda", "Dodangaslanda", "Etungahakotuwa", "Galgamuwa", "Giriulla", "Gokaralla", "Halmillawewa", "Heraliyawela", "Hindagolla", "Hiruwalpola", "Horambawa", "Hulogedara", "Hulugalla", "Ibbagamuwa", "llukhena", "Indulgodakanda", "Inguruwatta", "Iriyagolla", "Ithanawatta", "Kadigawa", "Kahapathwala", "Kalugamuwa", "Kanadeniyawala", "Kanattewewa", "Katupota", "Kekunagolla", "Keppitiwalana", "Kirimetiyawa", "Kirindigalla", "Kithalawa", "Kobeigane", "Kohilagedara", "Konwewa", "Kosdeniya", "Kosgolla", "Kotawehera", "Kudagalagamuwa", "Kudakathnoruwa", "Kuliyapitiya", "Kumbukgeta", "Kumbukwewa", "Kuratihena", "Kurunegala Town", "Labbala", "Lbbagamuwa", "Lonahettiya", "Madahapola", "Madakumburumulla", "Maduragoda", "Maeliya", "Mahagalkadawala", "Mahagirilla", "Mahamukalanyaya", "Mahananneriya", "Maharachchimulla", "Maho", "Makulpotha", "Makulwewa", "Malagane", "Malkaduwawa", "Malpitiya", "Mandapola", "Maspotha", "Mawathagama", "Meegalawa", "Meewellawa", "Melsiripura", "Metiyagane", "Minhettiya", "Minuwangete", "Mirihanegama", "Moragane", "Moragollagama", "Munamaldeniya", "Nabadewa", "Nagollagama", "Nagollagoda", "Nakkawatta", "Narammala", "Narangoda", "Nawatalwatta", "Nelliya", "Nikadalupotha", "Nikaweratiya", "Padeniya", "Padiwela", "Pahalagiribawa", "Pahamune", "Palukadawala", "Panadaragama", "Panagamuwa", "Panaliya", "Panliyadda", "Pannala", "Pansiyagama", "Periyakadneluwa", "Pihimbiya Ratmale", "Pihimbuwa", "Pilessa", "Polgahawela", "Polpitigama", "Pothuhera", "Puswelitenna", "Ridigama", "Sandalankawa", "Sirisethagama", "Siyambalagamuwa", "Solewewa", "Sunandapura", "Talawattegedara", "Tambutta", "Thalahitimulla", "Thalakolawewa", "Thalwita", "Thambagalla", "Tharana Udawela", "Thimbiriyawa", "Thorayaya", "Tisogama", "Torayaya", "Tuttiripitigama", "Udubaddawa", "Uhumiya", "Usgala Siyabmalangamuwa", "Wadakada", "Wadumunnegedara", "Wannilhalagama", "Wannirasnayakapura", "Warawewa", "Wariyapola", "Watuwatta", "Welawa Junction", "Welipennagahamulla", "Wellagala", "Wellarawa", "Wellawa", "Wennoruwa", "Weuda", "Wewagama", "Yakwila"};
    public String[] city_Puttalam = {"Your City", "Adippala", "Anamaduwa", "Andigama", "Angunawila", "Bangadeniya", "Baranankattuwa", "Battuluoya", "Bingiriya", "Bujjampola", "Chilaw", "Dankotuwa", "Dunkannawa", "Eluwankulama", "Ettale", "Ihala Kottaramulla", "Ihala Puliyankulama", "Kakkapalliya", "Kalpitiya", "Karativponparappi", "Karuwalagaswewa", "Katuneriya", "Kirimundalama", "Kudawewa", "Kumarakattuwa", "Kuruketiyawa", "Lihiriyagama", "Lunuwila", "Madampe", "Madurankuliya", "Mahauswewa", "Marawila", "Mundel", "Muttibendivila", "Nainamadama", "Nalladarankattuwa", "Nattandiya", "Nawagattegama", "Norachcholai", "Palaviya", "Pallama", "Palliwasalturai", "Pothuwatawana", "Puttalam Town", "Rajakadaluwa", "Saliyawewa Junction", "Tabbowa", "Talawila Church", "Toduwawa", "Udappu", "Udappuwa", "Uridyawa", "Uriyawa", "Vanathawilluwa", "Waikkal", "Watugahamulla", "Wennappuwa", "Wilpotha", "Yogiyana"};

    public String[] city_Kegalle = {"Your City", "Alawatura", "Algama", "Aluthnuwara", "Ambalakanda", "Ambulugala", "Amitirigala", "Ampagala", "Anhettigama", "Aranayake", "Aruggammana", "Atale", "Batuwita", "Beligala", "Berannawa", "Bopitiya", "Boralankada", "Bossella", "Bulathkohupitiya", "Damunupola", "Daraniyagala", "Debathgama", "Dedigama", "Dedugala", "Deewala Pallegama", "Dehiowita", "Deldeniya", "Deloluwa", "Deraniyagala", "Dewalegama", "Dewanagala", "Dombemada", "Dorawaka", "Dunumala", "Galapitamada", "Galatara", "Galigamuwa", "Galpatha", "Gantuna", "Gonagala", "Hakabellawaka", "Hakahinna", "Hakbellawaka", "Hawadiwela", "Helamada", "Hemmatagama", "Hettimulla", "Hewadiwela", "Hingula", "Hinguralakanda", "Hiriwadunna", "Imbulana", "Imbulgasdeniya", "Kabagamuwa", "Kannattota", "Kegalle Town", "Kehelpannala", "Kithulgala", "Kitulgala", "Kondeniya", "Kotiyakumbura", "Lewangama", "Mahapallegama", "Maharangalla", "Makehelwala", "Malalpola", "Maliboda", "Malmaduwa", "Mawanella", "Migastenna", "Miyanawita", "Molagoda", "Morontota", "Nelumdeniya", "Niyadurupola", "Noori", "Parape", "Pattampitiya", "Pitagaldeniya", "Rambukkana", "Ruwanwella", "Seaforth Colony", "Talgaspitiya", "Teligama", "Thatawella", "Tholangamuwa", "Thotawella", "Tulhiriya", "Tuntota", "Udagaldeniya", "Udapotha", "Udumulla", "Undugoda", "Ussapitiya", "Wahakula", "Waharaka", "Warakapola", "Watura", "Weeoya", "Wegalla", "Welihelatenna", "Weragala", "Yatagama", "Yatapana", "Yatiyantota", "Yattogoda"};
    public String[] city_Ratnapura = {"Your City", "Akarella", "Atakalanapnna", "Ayagama", "Balangoda", "Batatota", "Belihuloya", "Bolthumbe", "Bulutota", "Dambuluwana", "Dela", "Delwala", "Demuwatha", "Dodampe", "Doloswalakanda", "Dumbara Manana", "Eheliyagoda", "Ekamuthugama", "Elapatha", "Ellagawa", "Ellawala", "Embilipitiya", "Erepola", "Gabbela", "Gallella", "Gangeyaya", "Gawaragiriya", "Getahetta", "Gillimale", "Godagampola", "Godakawela", "Gurubewilagama", "Halpe", "Halwinna", "Handagiriya", "Hapugastenna", "Hatangala", "Hatarabage", "Hiramadagama", "Ihalagalagama", "Imbulpe", "Ittakanda", "Kahangama", "Kahawatte", "Kalawana", "Kalthota", "Karandana", "Karangoda", "Karawita", "Kella Junction", "Kiribbanwewa", "Kiriella", "Kolambageara", "Kolombugama", "Kolonna", "Kudawa", "Kuruwita", "Madalagama", "Madampe", "Mahagamakoloniya", "Mahawalatenna", "Makandura Sabara", "Matuwagalagama", "Meddekanda", "Minipura Dumbara", "Mitipola", "Morahela", "Mulendiyawala", "Nawalakanda", "Nivithigala", "Omalpe", "Opanayaka", "Padalangala", "Pallebedda", "Pambagolla", "Panamura", "Panawala", "Parakaduwa", "Pebotuwa", "Pelmadulla", "Pimbura", "Pinnawala", "Rajawaka", "Rakwana", "Ranwala", "Rassagala", "Ratna Hangamuwa", "Ratnapura Town", "Samanalawewa", "Sevanagala", "Sri Palabaddala", "Sudagala", "Teppanawa", "Tunkama", "Udakarawita", "Udaniriella", "Udawalawe", "Ullinduwawa", "Veddagala", "Vijeriya", "Waleboda", "Watapotha", "Waturawa", "Weligepola", "Welipathayaya", "Wewelwatta", "Wikiliya"};

    public String[] city_Galle = {"Your City", "Agaliya", "Ahangama", "Ahungalla", "Akmeemana", "Akuressa", "Aluthwala", "Ambalangoda", "Ampegama", "Amugoda", "Anangoda", "Angulugaha", "Ankokkawala", "Atakohota", "Avittawa", "Baddegama", "Balapitiya", "Banagala", "Batapola", "Benthota", "Boossa", "Dikkumbura", "Dodanduwa", "Elipitiya", "Ella Tanabaddegama", "Elpitiya", "Ethkandura", "Galle Town", "Gintota", "Godahena", "Gonagalpura", "Habaraduwa", "Haburugala", "Halvitigala Colony", "Hawpe", "Hikkaduwa", "Hiniduma", "Hiyare", "Ihalahewessa", "Ihala Walpola", "Imaduwa", "Induruwa", "Kahaduwa", "Kahawa", "Kananke Bazaar", "Karagoda", "Karandeniya", "Ketandola", "Koggala", "Kosgoda", "Kothalawala", "Kottawagama", "Kurundugahahethakma", "Madakumburamulla", "Magala North", "Magala South", "Magedara", "Malamura", "Malgalla Talangalla", "Mapalagama", "Mapalagama Central", "Mattaka", "Meda Keembiya", "Meetiyagoda", "Miriswatta", "Nagoda", "Nakiyadeniya", "Nawadagala", "Neluwa", "Nindana", "Opatha", "Panangala", "Pannimulla Panagoda", "Parana Thanayamgoda", "Pitigala", "Pitigala - North", "Porawagama", "Rantotuvila", "Talagampola", "Talpe", "Tawalama", "Thalgaswala", "Udalamatta", "Udugama", "Unawatuna", "Uragasmanhandiya", "Wackwella", "Walahanduwa", "Wanchawela", "Wanduramba", "Warukandeniya", "Weihena", "Yakkalamulla", "Yatalamatta"};
    public String[] city_Hambantota = {"Your City", "Ambalantota", "Angunakolapalassa", "Bandagiriya Colony", "Barawakumbuka", "Beliatta", "Beragama", "Beralihela", "Bowalagama", "Bundala", "Ellagala", "Gangulandeniya", "Getamanna", "Goda Koggalla", "Gonagamuwa Uduwila", "Gonnoruwa", "Hakuruwela", "Hambantota", "Hambantota Town", "Horewelagoda", "Hungama", "Ihala Beligala", "Ittademaliya", "Julampitiya", "Kahandamodara", "Kariyamaditta", "Katuwana", "Kawantissapura", "Kirama", "Kirinda", "Lunama", "Lunugamwehera", "Magama", "Mahagalwewa", "Mamadala", "Medamulana", "Middeniya", "Migahajandur", "Modarawana", "Mulkirigala", "Nakulugamuwa", "Netolpitiya", "Nihiluwa", "Padawkema", "Pahala Andarawewa", "Pallekanda", "Rammalawarapitiya", "Ranakeliya", "Ranmuduwewa", "Ranna", "Ratmalwala", "Ridiyagama", "Sooriyawewa", "Tangalle", "Tissamaharama", "Uda Gomadiya", "Udamattala", "Uswewa", "Vitharandeniya", "Walasmulla", "Weeraketiya", "Weerawila", "Weerawila New Town", "Wekandawela", "Weligatta", "Yatigala"};
    public String[] city_Matara = {"Your City", "Akuressa", "Alapaladeniya", "Aparekka", "Aturaliya", "Bengamuwa", "Beralapanathara", "Bopagoda", "Dampahala", "Deegala Lenama", "Deiyandara", "Dellawa", "Denagama", "Denipitiya", "Deniyaya", "Derangala", "Devinuwara", "Devundara", "Dikwella", "Diyagaha", "Diyalape", "Gandara", "Godagama", "Godapitiya", "Gomila Mawarala", "Hakmana", "Handugala", "Hithetiya", "Horapawita", "Kalubowitiyana", "Kamburugamuwa", "Kamburupitiya", "Karagoda Uyangoda", "Karaputugala", "Karatota", "Kekanadura", "Kiriweldola", "Kiriwelkele", "Kolawenigma", "Kotapola", "Kottegoda", "Lankagama", "Makandura", "Maliduwa", "Malimboda", "Maramba", "Matara", "Matara Town", "Mediripitiya", "Miella", "Mirissa", "Modara", "Moragala Kirillapone", "Morawaka", "Mulatiyana Junction", "Nadugala", "Naimana", "Narawelpita", "Nawimana", "Nupe", "Pahala Millawa", "Palatuwa", "Pamburana", "Paragala", "Parapamulla", "Pasgoda", "Penetiyana", "Pitabeddara", "Pothdeniya", "Puhulwella", "Radawela", "Ransegoda", "Ratmale", "Rotumba", "Siyambalagoda", "Sultanagoda", "Talaramba", "Thelijjawila", "Thihagoda", "Thudawa", "Urubokka", "Urugamuwa", "Urumutta", "Uyanwatta", "Viharahena", "Walakanda", "Walasgala", "Walgama", "Wallasmulla", "Waralla", "Weligama", "Welihinda", "Wilpita", "Yatiyana"};

    public String[] city_Badulla = {"Your City", "Akkarasiyaya", "Aluketiyawa", "Aluththaramma", "Aluttaramma", "Ambadandegama", "Ambagahawatte", "Ambagasdowa", "Amunumulla", "Arawa", "Arawakumbura", "Arawatta", "Atakiriya", "Badulla Town", "Baduluoya", "Ballaketuwa", "Bambarapana", "Bandarawela", "Beramada", "Bibilegama", "Bogahakumbura", "Boragas", "Boralanda", "Bowela", "Dambana", "Demodara", "Diganatenna", "Dikkapitiya", "Dimbulana", "Divulapelessa", "Diyathalawa", "Dulgolla", "Egodawela", "Ella", "Ettempitiya", "Gadunna", "Galauda", "Galedanda", "Galporuyaya", "Gamewela", "Gawarawela", "Girandurukotte", "Godunna", "Guruthalawa", "Haldummulla", "Hali", "Hali-ela", "Hangunnawa", "Haputale", "Hawanakumbura", "Hebarawa", "Heeloya", "Helahalpe", "Helapupula", "Hewanakumbura", "Hingurukaduwa", "Hopton", "Idalgashinna", "Jangulla", "Kabillawela", "Kahataruppa", "Kalubululanda", "Kalugahakandura", "Kalupahana", "Kandaketiya", "Kandegedara", "Kandepuhulpola", "Kebillawela", "Kendagolla", "Keppetipola", "Keselpotha", "Ketawatta", "Kiriwanagama", "Koslanda", "Kotamuduna", "Kuruwitenna", "Kuttiyagolla", "Landewela", "Liyanagahawela", "Lunugala", "Lunuwatta", "Madulsima", "Mahiyangana", "Mahiyanganaya", "Makulella", "Malgoda", "Maliyadda", "Mapakadawewa", "Maspanna", "Maussagolla", "Medawelagama", "Medawela Udukinda", "Meegahakivula", "Metigahatenna", "Mirahawatta", "Miriyabedda", "Miyanakandura", "Namunukula", "Narangala", "Nelumgama", "Nikapotha", "Nugatalawa", "Ohiya", "Pahalarathkinda", "Pallekiruwa", "Passara", "Pathanewatta", "Pattiyagedara", "Pelagahatenna", "Perawella", "Pitamaruwa", "Pitapola", "Poonagala", "Puhulpola", "Ratkarawwa", "Rideemaliyadda", "Rilpola", "Silmiyapura", "Sirimalgoda", "Sorabora Colony", "Soragune", "Soranathota", "Spring Valley", "Taldena", "Tennepanguwa", "Timbirigaspitiya", "Uduhawara", "Uraniya", "Uva Deegalla", "Uva Karandagolla", "Uva Mawelagama", "Uvaparanagama", "Uva Tenna", "Uva Tissapura", "Uva Uduwara", "Welimada", "Wewatta", "Wineethagama", "Yalagamuwa", "Yalwela"};
    public String[] city_Monaragala = {"Your City", "Angunakolawewa", "Ayiwela", "Badalkumbura", "Baduluwela", "Bakinigahawela", "Balaharuwa", "Bibile", "Buddama", "Buttala", "Dambagalla", "Diyakobala", "Dombagahawela", "Ekamutugama", "Ekiriyankumbura", "Ethimalewewa", "Ettiliwewa", "Galabedda", "Hambegamuwa", "Hulandawa", "Inginiyagala", "Kandaudapanguwa", "Kandawinna", "Kataragama", "Kiriibbanwewa", "Kotagama", "Kotawehera Mankada", "Kotiyagala", "Kudaoya", "Kumbukkana", "Mahagama Colony", "Marawa", "Mariarawa", "Medagana", "Monaragala", "Monaragala Town", "Moretuwegama", "Nakkala", "Nannapurawa", "Nelliyadda", "Nilgala", "Obbegoda", "Okkampitiya", "Pangura", "Pitakumbura", "Randeniya", "Ruwalwela", "Sella Kataragama", "Sewanagala", "Siyambalagane", "Siyambalanduwa", "Suriara", "Tanamalila", "Tanamalwila", "Uva Gangodagama", "Uva Kudaoya", "Uva Pelwatta", "Warunagama", "Wedikumbura", "Weherayaya Handapanagala", "Wellawaya", "Wilaoya"};

    public String[] city_Colombo = {"Your City", "Colombo 01 - Fort", "Colombo 02 - Slave Island & Union Place", "Colombo 03 - Kollupitiya", "Colombo 04 - Bambalapitiya", "Colombo 05 - Havelock Town & Kirulapona", "Colombo 06 - Wellawatte & Pamankada", "Colombo 07 - Cinnamon Gardens", "Colombo 08 - Borella", "Colombo 09 - Dematagoda", "Colombo 10 - Maradana", "Colombo 11 - Pettah", "Colombo 12 - Hultsdorf", "Colombo 13 - Kotahena & Kochchikade", "Colombo 14 - Grandpass", "Colombo 15 - Modera & Mattakkuliya", "Aggona", "Angoda", "Angulana", "Athurugriya", "Attidiya", "Avissawella", "Battaramulla", "Beddagana", "Bellanvila", "Bokundara", "Bope", "Bopitiya", "Boralesgamuwa", "Dedigamuwa", "Dehiwala", "Delkanda", "Egoda Uyana", "Embuldeniya", "Gangodawila", "Godagama", "Gothatuwa", "Habarakada", "Hanwella", "Himbutana", "Hiripitya", "Hokandara", "Homagama", "Jambugasmulla", "Kaduwela", "Kahathuduwa", "Kalubowila", "Katubedda", "Kawdana", "Kesbewa", "Kiriwattuduwa", "Kohuwala", "Kolonnawa", "Kosgama", "Koswatta", "Kotikawatta", "Kottawa", "Kotte", "Lunawa", "Madapatha", "Madiwela", "Maharagama", "Malabe", "Mattegoda", "Meegoda", "Mirihana", "Moratuwa", "Mount Lavinia", "Mullegama", "Mulleriyawa", "Mulleriyawa New Town", "Napawela", "Nawala", "Nawinna", "Nedimala", "Nugegoda", "Obesekarapura", "Orugodawatta", "Padukka", "Pagoda", "Paliyagoda", "Pannipitiya", "Pelawatta", "Pepiliyana", "Piliyandala", "Pitipana Homagama", "Polgasowita", "Rajagiriya", "Rathmalana", "Ratmalana", "Rattanapitiya", "Sapugaskande", "Sedawatte", "Siddamulla", "Sri Jayawardenapura Kotte", "Talangama", "Talawatugoda", "Thalawathugoda", "Udahamulla", "Waga", "Watareka", "Welikada", "Welivita", "Wellampitiya", "Werahera", "Wijerama"};
    public String[] city_Gampaha = {"Your City", "Alawala", "Ambagaspitiya", "Ambepussa", "Amuhena", "Andiambalama", "Attanagalla", "Badalgama", "Bemmulla", "Biyagama", "Buthpitiya", "Danowita", "Debahera", "Dekatana", "Delgoda", "Demalagama", "Dewalapola", "Divulapitiya", "Divuldeniya", "Dompe", "Dunagaha", "Ekala", "Ellakkala", "Essella", "Gampaha Town", "Ganemulla", "Gonawala", "Heiyanthuduwa", "Hendala", "Henegama", "hala Madampella", "Ja-Ela", "Kadawatha", "Kalagedihena", "Kaleliya", "Kaluaggala", "Kandana", "Katana", "Katunayake", "Kelaniya", "Kimbulapitiya", "Kiribathgoda", "Kirindiwela", "Kitulwala", "Kotadeniyawa", "Kotugada", "Lunugama", "Mabodala", "Mabole", "Madelgamuwa", "Mahabage", "Makola", "Malwana", "Mawaramandiya", "Mellawagedara", "Minuwangoda", "Mirigama", "Mudungoda", "Naiwella", "Negombo", "Nikahetikanda", "Nittambuwa", "Pallewela", "Pamunugama", "Pamunuwatta", "Pasyala", "Peliyagoda", "Pugoda", "Radawadunna", "Raddolugama", "Ragama", "Ranala", "Rukmale", "Seeduwa", "Siyambalape", "Udugampola", "Urapola", "Uswetakeiyawa", "Vayangoda", "Veyangoda", "Walpita", "Walpola", "Wanaluwewa", "Wattala", "Weliweriya", "Weweldeniya", "Yakkala", "Yatiyana"};
    public String[] city_Kalutara = {"Your City", "Agalawatta", "Alubomulla", "Aluthgama", "Arukgoda", "Athwelthota", "Aubomulla", "Awiththawa", "Baduraliya", "Bandaragama", "Bekkegama", "Bellana", "Beruwala", "Bolossagama", "Bombuwala", "Boralugoda", "Bulathsinhala", "China Fort", "Daluwatta", "Dediyawala", "Delduwa", "Dharga Town", "Dibbedda", "Diggala", "Diyalagoda", "Dodamgoda", "Dodangoda", "Dombagoda", "Egal Oya", "Eluwila", "Galpatha", "Galthude", "Gamagoda", "Gonapola Junction", "Gorakana", "Goraka Pola", "Govinna", "Halkandawila", "Haltota", "Halwatura", "Handapangoda", "Hedigalla Colony", "Hirana", "Horana", "Horawala", "Horethuduwa", "Ingiriya", "Ittapana", "Kalamulla", "Kaludewala", "Kalugala", "Kalutara", "Kalutara Town", "Kaluwamodara", "Kananwila", "Katukurunda", "Kehelwatta", "Keselwatta", "Kethhena", "Kiriberiya", "Kitulgoda", "Koholana", "Kuruppu Mulla", "Maggona", "Mahagama", "Mahakalupahana", "Malamulla", "Malegoda", "Maradana", "Mathugama", "Matugama", "Meegahatenna", "Meegama", "Melegama", "Millaniya", "Millewa", "Miwanapalana", "Molkawa", "Molligoda", "Moragalla", "Morontuduwa", "Mun Hena", "Nagas Handiya", "Narthupana", "Neboda", "Omaththa", "Owitigala", "Paiyagala", "Panadura", "Pannila", "Paragastota", "Paragoda", "Paraigama", "Paraththa", "Pibura", "Pohaddaramulla", "Pokunuwita", "Polgampola", "Poruwedanda", "Pothuwila", "Remunagoda", "Serupita", "Tebuwana", "Thalpitiya", "Thanthirimulla", "Thebuwana", "Thudugala", "Uduwara", "Wadduwa", "Walallawita", "Walana", "Walathara", "Waskaduwa", "Wehada", "Welipenna", "Welmilla Junction", "Weththewa", "Wettumakade", "Yagirala", "Yatadolawatta", "Yatawara Junction"};


    //--Blood for
    public String[] bloodFor = {"Requesting for whom?", "me", "Family Member", "Relative", "Friend", "My Employee", "Neighbor"};
    //--Request District
    public String[] requestDistrict = {"Select District", "Kandy", "Matale", "Nuwara Eliya", "Ampara", "Batticaloa", "Trincomalee", "Anuradhapura", "Polonnaruwa", "Jaffna", "Kilinochchi", "Mannar", "Mulativu", "Vavuniya", "Kurunegala", "Puttalam", "Kegalle", "Ratnapura", "Galle", "Hambantota", "Matara", "Badulla", "Monaragala", "Colombo", "Gampaha", "Kalutara"};


    //explore donors
    public String[] exDonor_bloodGroup = {"All", "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"};
    public String[] exDonor_province = {"Select Province", "Central", "Eastern", "North Central", "Northern", "North Western", "Sabaragamuwa", "Southern", "Uva", "Western"};
    public String[] exDonor_districts_Central = {"All", "Kandy", "Matale", "Nuwara Eliya"};
    public String[] exDonor_districts_Eastern = {"All", "Ampara", "Batticaloa", "Trincomalee"};
    public String[] exDonor_districts_North_Central = {"All", "Anuradhapura", "Polonnaruwa"};
    public String[] exDonor_districts_Northern = {"All", "Jaffna", "Kilinochchi", "Mannar", "Mulativu", "Vavuniya"};
    public String[] exDonor_districts_North_Western = {"All", "Kurunegala", "Puttalam"};
    public String[] exDonor_districts_Sabaragamuwa = {"All", "Kegalle", "Ratnapura"};
    public String[] exDonor_districts_Southern = {"All", "Galle", "Hambantota", "Matara"};
    public String[] exDonor_districts_Uva = {"All", "Badulla", "Monaragala"};
    public String[] exDonor_districts_Western = {"All", "Colombo", "Gampaha", "Kalutara"};

    //ambulance, blood _bank
    public String[] all_districts = {"All", "Kandy", "Matale", "Nuwara Eliya", "Ampara", "Batticaloa", "Trincomalee", "Anuradhapura", "Polonnaruwa", "Jaffna", "Kilinochchi", "Mannar", "Mulativu", "Vavuniya", "Kurunegala", "Puttalam", "Kegalle", "Ratnapura", "Galle", "Hambantota", "Matara", "Badulla", "Monaragala", "Colombo", "Gampaha", "Kalutara"};
}
